### ISSUE TITLE
not compatible with OJS 3.1.2? 

### ISSUE THREAD

**Issue by carzamora** [NateWr/defaultManuscript#18]
Hi Nate, 

I think the theme is not compatible with the last release, can you confirm?

thanks!

**Comment by carzamora** [comment]
my mistake, it is compatible! sorry, maybe my problem is one little customization...

**Comment by ritacvn** [comment]
hey how did you make it work? can you explain me? I am having this problem

**Comment by carzamora** [comment]
Hi, 

Yes, it's working fine! In my case, I changed the code in some files. Then, when I update to OJS 3.1.2, I did have some issues, but I just tried one more time with the original code and have no problems again. So, I can suggest you install or update the Theme from gallery plugins inside OJS.

**Comment by ritacvn** [comment]
Nice!

**Comment by ritacvn** [comment]
Nice, but what code have you changed? I already tried to install from the theme gallery and It didn't work.

**Comment by carzamora** [comment]
Oh, I don't remember what code I change, but it is not important because the code I change was the problem! My problem was resolved when I return all theme to the original code! I hope you understand...
