### ISSUE TITLE
Long URLs not wrapping and overlapping contents in sidebar

### ISSUE THREAD

**Issue by israelcefrin** [NateWr/defaultManuscript#20]
Hit @NateWr ,

In some browsers, long URLs in citations are not wrapping appropriately. This causes links to overlap with Copyright Notice statements in the right sidebar.

I've fixed it including the following chunk in a stylesheet file and uploaded it:
```
div.item.references a {
	overflow-wrap: break-word
}
```

But I'm not sure if just add it to CSS article_details or you may have another CSS file for this adjustments. Let me know whether you think I should create a PR for that.

Cheers,
Israel

**Comment by NateWr** [comment]
Thanks @israelcefrin. If this happens in `defaultManuscript` than it also happens in the default theme and we should fix it there. Do you mind filing an issue in the pkp-lib repository for this?

**Comment by NateWr** [comment]
I think this was fixed in default.
