### ISSUE TITLE
Issue with Arabic layout

### ISSUE THREAD

**Issue by amandastevens** [NateWr/defaultManuscript#25]
A PKP|PS hosted client whose OJS journal is in Arabic noticed that when the Manuscript theme is enabled there is overlapping text and a line down the middle of the page.  In Arabic the page reads from right to left, so content is in a different place. Is it possible to adapt the theme to work with this layout?

![OJS-arabic-manuscript](https://user-images.githubusercontent.com/35044512/78300126-3ba91380-74f4-11ea-9b80-ca27d6dc2060.png)

**Comment by hkamareddineiiit** [comment]
Thanks Amanda. I just want to point out that Arabic is read from right to left not left to right. I hope this issue will be resolved soon.

Thanks!

**Comment by amandastevens** [comment]
Oops!  Thanks for pointing that out.  I will edit the above description.

**Comment by NateWr** [comment]
Ahalan wasahalan, ya @hkamareddineiiit! @amandastevens can you check what version of the theme you're using? When I test locally, the lines are correctly adjusted for RTL:

![manuscript](https://user-images.githubusercontent.com/2306629/78547388-f0924780-77f6-11ea-8f71-205ee1727b83.png)

I noticed that the user nav menu is not repositioned, though, and fixed that in https://github.com/NateWr/defaultManuscript/commit/7e97c7153e7fd0f13ba1dfd50ebfd4e51aff0d5e. It now looks like:

![manuscript-menu](https://user-images.githubusercontent.com/2306629/78547441-030c8100-77f7-11ea-85ff-8749a169c258.png)

**Comment by amandastevens** [comment]
Thanks, @NateWr, I assigned this to the PS systems team to check the version and apply the patch.
