### ISSUE TITLE
defaultManuscript style problem

### ISSUE THREAD

**Issue by gkmnarslan** [NateWr/defaultManuscript#27]
Hi,

I use OJS3.2.03. I set up the theme but face the unstyled, see https://forum.pkp.sfu.ca/t/defaultmanuscript-problem/60412

Please help.

**Comment by akinayturan** [comment]
Hello, I have 2 questions

1. Is the theme you downloaded one of the releases version (from here https://github.com/NateWr/defaultManuscript/releases). 

2. Which language(s) do you use ?

**Comment by gkmnarslan** [comment]
Thank you for your quick reply. 
I use OJS 3.2.03 and defaultManuscript 1.0.3

**Comment by akinayturan** [comment]
When I check his messages, we see that you are using filezilla.
I use filezilla too, I will tell you my way

-> after download the defaultManuscript 1.0.3  as a zip
-> upload directly to the defaultManuscript-1.0.3.zip through the Plugin Gallery of ojs
-> unzip from your panel (cpanel or plesk) 
-> *** rename defaultManuscript-1.0.3 file as a defaultManuscript  ***
-> active theme as a plugins from ojs panel
-> select as a theme

*** i think this may the problem

**Comment by gkmnarslan** [comment]
I am currently setting: http://journalppw.com/index.php/JPPW
But it continues.

**Comment by gkmnarslan** [comment]
Also, I can not upload directly to the defaultManuscript-1.0.3.zip through the Plugin Gallery of ojs. I face the problem:
Notification
The uploaded plugin archive does not contain a folder that corresponds to the plugin name.

**Comment by NateWr** [comment]
I recommend you don't download the theme directly from GitHub. Search for the theme in the plugin gallery in your OJS instance (Settings > Website > Plugins > Plugin Gallery) and install it from there.

**Comment by gkmnarslan** [comment]
Hi,
I tried but cannot install it. I click the "Are you sure you wish to install this plugin?" and with. After re-freshing the page, I see the "The uploaded plugin archive does not contain a folder that corresponds to the plugin name."

**Comment by NateWr** [comment]
Hmm, I've just checked the release package and it seems ok. Are you downloading the file and then uploading it? Or finding it through through the plugin gallery?

**Comment by gkmnarslan** [comment]
I download and upload via Filezilla or File manager (Cpanel). Then, I active it. I checked the other themes, there is no problem. I only face with this.

**Comment by gkmnarslan** [comment]
Hi again,
I solved the problem. I deleted all themes. then, I first uploaded the default. I started with it. Next, I set up the child. It is ok. 
Thank you Akin and NateWr.
