### ISSUE TITLE
plugin installation doesn't work on the OJS vagrant machine

### ISSUE THREAD

**Issue by trenkert** [NateWr/defaultManuscript#3]

**Comment by NateWr** [comment]
Please provide a more detailed bug report. I don't use the OJS vagrant machine.

**Comment by trenkert** [comment]
![df17b75a-50ec-41f5-9653-048262ec2a6d](https://cloud.githubusercontent.com/assets/143727/25667323/75dd32fc-3023-11e7-98f3-c51f74fddeff.png)

This is my configuration. When I click on Plugin Gallery, I can see the manuscript plugin. When I click on it, I can click on install. However, nothing happens after that.

**Comment by NateWr** [comment]
I'm afraid I'm not too familiar with the Plugin Gallery. You may need to manually install the release package:

https://github.com/NateWr/defaultManuscript/releases

**Comment by trenkert** [comment]
I did that already. The plugin shows up in the list of installed plugins and can be activated/deactivated. However, there are no new themes to choose from. Also, it cannot be uninstalled from the menu. It seems like it somehow is only partially registered by the system.

**Comment by mittinatten** [comment]
Hi, I had the same problem. I installed the plugin manually by downloading the archive and it showed up in the installed plugins list, but not among the available themes after I activated it. The solution was to download the "custom" zip from the release, i.e. https://github.com/NateWr/defaultManuscript/releases/download/1.0.2/defaultManuscript-1.0.2.zip, and not the one automatically generated by Github (https://github.com/NateWr/defaultManuscript/archive/1.0.2.tar.gz).

**Comment by NateWr** [comment]
Ah, yes, it will probably cause a problem if you just download hte automatic packages that GitHub creates, because it modifies the directory name. Always look for the official release packages:

https://github.com/NateWr/defaultManuscript/releases

And make sure to get the one compatible with  your version of OJS:

https://github.com/NateWr/defaultManuscript#version-compatibility

**Comment by mittinatten** [comment]
Does that mean it can't be added as a submodule either?

**Comment by NateWr** [comment]
Submodule should be fine. We don't have any build step for this theme. Just be aware that the `master` branch is not necessarily compatible with the latest release or the `master` branches of pkp-lib and ojs. You will probably want to peg it to the release commit to be certain.

Also, make sure it slots into the theme directory with a folder name of `defaultManuscript`.
