### ISSUE TITLE
Manuscript Theme Not Work on ojs 3.2.1-4

### ISSUE THREAD

**Issue by goesmvn** [NateWr/defaultManuscript#33]
Hello i got issues on ojs 3.2.1-4 it not working the error is CSS not found or not load

Request URL: https://ejournal.ppb.ac.id/index.php/jpar/$$$call$$$/page/page/css?name=stylesheet
Request Method: GET
Status Code: 500 
Remote Address: 202.74.238.213:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by NateWr** [comment]
Hi @goesmvn, I was unable to reproduce this. I suggest trying to reinstall the Manuscript theme from the plugin gallery to see if that fixes it.
