### ISSUE TITLE
locale it_IT all msgid problem

### ISSUE THREAD

**Issue by eniocarboni** [NateWr/defaultManuscript#35]
Only in locale it_IT (locale/it_IT/locale.po) all msgid tag has a suffix "**child**" which should not exist.
Eg:
msgid "plugins.themes.defaultManuscript**child**.name" shoud be msgid "**plugins.themes.defaultManuscriptchild**.name"

**Comment by NateWr** [comment]
Thanks for reporting, @eniocarboni! I've fixed that now.
