### ISSUE TITLE
L-to-R: User menu blocks Journal Title and Logo

### ISSUE THREAD

**Issue by pmangahis** [NateWr/defaultManuscript#36]
When a multi-lingual journal using English and L-to-R language (i.e., Arabic) switches between languages on the front end, the user menu does not adjust properly

English:
![image](https://user-images.githubusercontent.com/50342731/124038405-f05f0880-d9b5-11eb-8547-624bcf9d0826.png)

Arabic
![image](https://user-images.githubusercontent.com/50342731/124038445-fce36100-d9b5-11eb-9e60-bd33735c3dd3.png)

The issue was observed in OJS 3.2 and 3.3 and appears to be corrected already on the Default theme.

**Comment by saalam** [comment]
In addition to the above, the search button appears as the very first item in the main navigation menu while it should be appear the last one when the theme is using a RTL language.

![Search](https://user-images.githubusercontent.com/16186009/211908492-46793655-b662-4942-a672-b92a1f070f5b.JPG)

**Comment by NateWr** [comment]
Thanks @pmangahis and @saalam. These issues effected the default theme and have been fixed there. @pmangahis your issue was fixed at https://github.com/pkp/pkp-lib/issues/7733 and @saalam I've just fixed your issue at https://github.com/pkp/pkp-lib/issues/8699.

These fixes will go out with 3.4.
